### ISSUE TITLE
Minor Question on Eq.4

### ISSUE THREAD

**Issue by HanGuo97** [team-approx-bayes/dl-with-bayes#8]
Hi, thanks for this awesome repository and paper -- I really enjoyed reading it!

I have a quick question on Eq.4 in the [paper](https://arxiv.org/pdf/1906.02506.pdf) and would like to have some clarification. Notably, why do we use

$$\boldsymbol{\Sigma}_t:=\operatorname{diag} \left(1 /\left(N\left({s}_{t} + \tilde{\delta}\right)\right)\right), \tilde{\delta} := \tau \delta / N$$

instead of,

$$\boldsymbol{\Sigma}_t:=\operatorname{diag} \left(1 /\left({\color{blue}\frac{N}{\tau}}\left({s}_{t} + \tilde{\delta}\right)\right)\right), \tilde{\delta} := \tau \delta / N$$

which is analogous to Eq.9 in [this paper](https://arxiv.org/pdf/1712.02390.pdf)?

(Obviously, if $\tau = 1$, then they are the same.)

Thanks in advance for the help!

**Comment by emtiyaz** [comment]
The two methods are quite different in details, because the NNG paper uses Fisher with damping, while Eq. 4 in our paper is just a diagonal version. Perhaps Appendix A in [our paper](https://arxiv.org/pdf/1906.02506.pdf) is a bit closer to what is done in NNG (we compare to this method on ImageNet). Not sure if the KFAC implementation is also here in the repo, but you can look into that to see if it is indeed different (I don't know).

**Comment by HanGuo97** [comment]
Thanks for the response. Apology for not making it clear enough. I'm talking about the diagonal version of NNG (which I believe is connected to this work), and only about the coefficient (shown in blue earlier). In Appendix A you referred to, you also used something like (with symbols rearrangements, naive simplification, and some minor changes),

$$\boldsymbol{\Sigma}t:=\operatorname{diag} \left(1 /\left({\color{blue}\frac{N}{\tau}}\left(...\right)\right)\right)$$

Are both $N$ and $N/\tau$ correct, or should practitioners use one of them?

**Comment by emtiyaz** [comment]
My guess would be that only one of them is correct. The other one gives variances that are either multiplied/divided by tau. Note that the MLE is unaffected by tau, but the Bayesian solution is sensitive to it. This is by design because tau is trading off the likelihood vs prior, something that is crucial for the variance. 

I will also ask @kazukiosawa what he implemented in the code. Let's see what he says.

**Comment by kazukiosawa** [comment]
I have implemented it with $N/\tau$ scaling.

`std_scale` initialized [here](https://github.com/cybertronai/pytorch-sso/blob/master/torchsso/optim/vi.py#L78), which will be multiplied to the std for sampling Gauss noise [here](https://github.com/cybertronai/pytorch-sso/blob/master/torchsso/curv/curvature.py#L246), corresponds to $\sqrt{\tau/N}$.


We've observed that making this `std_scale` (i.e., $\tau$) smaller was necessary to stabilize the training, especially at the beginning of the training. 

$\tau$ will be 1 at the end of training for both VOGN and Noisy K-FAC in our settings. This is done in the `adjust_kl_weighting` function defined [here](https://github.com/cybertronai/pytorch-sso/blob/master/torchsso/optim/vi.py#L150).
![image](https://user-images.githubusercontent.com/7961228/180970447-53b3ddae-a3c0-4be4-ad08-788e20cf3e9c.png)

**Comment by HanGuo97** [comment]
Thanks for the detailed explanations and information! In that sense, the line below equation 4 in the paper was just a typo -- good to know.
